### ISSUE TITLE
Better representation of Array type

### ISSUE THREAD

**Issue by DVSoftware** [CoaPsyFactor/typesafe#1]
Instead of specifying an Array item types as itemType, why not specify the array as:

```
{
    type: [{
        type: String,
    }],
}
```

**Comment by DVSoftware** [comment]
Or even
```
{
    type: Array({
        type: String,
    }),
}
```

Which is basically the same as above, but cleaner

**Comment by zivanovica** [comment]
I agree- updates were made, to define array type with item properties use 
``
{
    type: Array({ type: String, allowNull: false })
}
``
